model_params: 
  z_encoder:
      n_layers: 1
      n_latent: 24
      n_hidden: 512
      dropout: 0
  l_encoder:
      n_layers: 1
      n_hidden: 512
      dropout: 0
  discriminator:
      n_layers: 1
      n_hidden: 512
      dropout: 0
  decoder:
      n_layers: 1
      n_hidden: 512
      dropout: 0


data_params: 
  name: 'sampleName' # The name of your dataset.
  data_path: "../data/sampleName" # The path of the input dataset. Should be a directory.
  binary: [False, False] # Whether each modality should be binarized. 
  normalize: [False, False] # Whether each modality should be normalized. 
  log_variational: [False, False] # Whether each modality should be log normalized.
  dims: [[0, 13263],[13263,89119]] # The dimension range of the each modality.
  reconstruction_loss: ["zinb", "nb"] # The temporary distribution for each modality 
  min_peaks: 0 # The minimum percentage of features that can be detected in a cell.  
  min_cells: 0 # The minimum percentage of cells with null-zero values for each feature.
  max_cells: 1 # The maximum percentage of cells with null-zero values for each feature. 
  n_batch: 1 # The number of batches.
  labeled: False # Whether the cell-type labels are provided.
  selective_weight: 1 # The weight of selected features indicated in the feature_discriminator.txt file.


exp_params: 
  seed: 42
  device: "cuda:0"

trainer_params: 
  early_stop: False
  min_delta: 0.2
  patience: 50
  accelerator: "auto"
  n_epochs: 1000
  warmup_epochs: 50
  batch_size: 128
  lr_e: 0.0001
  lr_d: 0.0001
  weight_decay: 0.000001
  decay_lr: 0.75
  eps: 0.01
  

clustering_params:  
  alg: 'louvain'
  n_louvain: 10 
  plot: 'tsne'
  
    
    
