model_params:
  z_encoder:
      n_layers: 1
      n_latent: 24
      n_hidden: 512
      dropout: 0.0
  l_encoder:
      n_layers: 1
      n_hidden: 512
      dropout: 0.0
  discriminator:
      n_layers: 1
      n_hidden: 512
      dropout: 0
  decoder:
      n_layers: 1
      n_hidden: 512
      dropout: 0


data_params:
  name: 'scChip_K27_K36_K4m1'
  data_path: "../data/scChip_K27_K36_K4m1"
  binary: [False, False,False]
  normalize: [False, False,False]
  log_variational: [False, False,False]
  dims: [[59091, 74940], [0, 59091], [74940, 150751]]
  reconstruction_loss: ["zinb", "zinb", "zinb"]
  min_peaks: 0 
  min_cells: 0 
  max_cells: 1
  n_batch: 1
  labeled: True
  selective_weight: 1


exp_params:
  seed: 42
  device: "cuda:0"

trainer_params:
  early_stop: False
  accelerator: "auto"
  n_epochs: 1000
  warmup_epochs: 50
  batch_size: 128
  lr_e: 0.0001
  lr_d: 0.0001
  weight_decay: 0.000001
  decay_lr: 0.75
  eps: 0.01
  

clustering_params:  
  alg: 'louvain'
  n_louvain: 10 
  plot: 'umap'
  
    
    
